# Generated by Django 4.2.16 on 2025-08-05 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='invite_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='invite_token',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='block_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='workspaces.folder'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='document',
            table=None,
        ),
        migrations.AlterModelTable(
            name='folder',
            table=None,
        ),
        migrations.AlterModelTable(
            name='workspace',
            table=None,
        ),
        migrations.AlterModelTable(
            name='workspacemember',
            table=None,
        ),
    ]
