# Generated by Django 4.2.16 on 2025-08-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_document__user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='_user',
        ),
    ]
