# Generated by Django 4.2.16 on 2025-08-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_remove_document__user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.JSONField(default={'blocks': [{'text': ''}]}),
        ),
    ]
